Projet_Isi/Projet_Isi/Models/Metier/Cours.cs
namespace Projet_Isi.Models.Metier
{
    public class Cours
    {
        private int id_cours;
        private string nom;
        private string description;
        private string nom_prof;
        private int duree;
        private DateTime date;

        public int Id_cours { get => id_cours; set => id_cours = value; }
        public string Nom { get => nom; set => nom = value; }
        public string Description { get => description; set => description = value; }
        public string Nom_prof { get => nom_prof; set => nom_prof = value; }
        public int Duree { get => duree; set => duree = value; }
        public DateTime Date { get => date; set => date = value; }
    }
}

Projet_Isi/Projet_Isi/Controllers/CoursController.cs
using Microsoft.AspNetCore.Mvc;
using Projet_Isi.Models.Dao;
using Projet_Isi.Models.MesExceptions;
using Projet_Isi.Models.Metier;

namespace Projet_Isi.Controllers
{
    public class CoursController : Controller
    {
        public IActionResult Index()
        {
            System.Data.DataTable Cours = null;
            try
            {
                Cours = ServiceCours.GetTousLesCours();
            }
            catch (MonException e)
            {
                ModelState.AddModelError("Erreur", "Erreur lors de la récupération des Cours:" + e.Message);
            }

            return View(Cours);
        }

        public IActionResult Modifier(int id)
        {
            Cours unCours = null;
            try
            {
                unCours = ServiceCours.GetunCours(id.ToString());
                return View(unCours);
            }
            catch (MonException e)
            {
                return NotFound();
            }
        }

        [HttpPost]
        public IActionResult Modifier(Cours unCours)
        {
            try
            {
                ServiceCours.UpdateCours(unCours);
                return RedirectToAction("Index");
            }
            catch (MonException e)
            {
                return NotFound();
            }
        }

        public IActionResult Supprimer(int id)
        {
            Cours unCours = null;
            try
            {
                unCours = ServiceCours.GetunCours(id.ToString());
                if (unCours == null)
                {
                    return NotFound();
                }
                return View(unCours);
            }
            catch (MonException e)
            {
                return NotFound();
            }
        }

        [HttpPost, ActionName("Supprimer")]
        [ValidateAntiForgeryToken]
        public IActionResult ConfirmerSuppression(int id)
        {
            try
            {
                ServiceCours.SupprimerCours(id);
                return RedirectToAction("Index");
            }
            catch (MonException e)
            {
                return NotFound();
            }
        }

        public IActionResult Ajouter()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Ajouter(Cours unCours)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    ServiceCours.AjouterCours(unCours);
                    return RedirectToAction("Index");
                }
            }
            catch (MonException e)
            {
                ModelState.AddModelError("Erreur", "Erreur lors de l'ajout du Cours : " + e.Message);
            }

            return View(unCours);
        }


    }
}

Projet_Isi/Projet_Isi/Views/Cours/Ajouter.cshtml
@model Projet_Isi.Models.Metier.Cours

@{
    ViewData["Title"] = "Ajouter un Cours";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Ajouter un Cours</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <!-- Nom du Cours -->
    <div class="form-group">
        @Html.LabelFor(model => model.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
        </div>
    </div>

    <!-- Description -->
    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <!-- Nom du Prof -->
    <div class="form-group">
        @Html.LabelFor(model => model.Nom_prof, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nom_prof, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nom_prof, "", new { @class = "text-danger" })
        </div>
    </div>

    <!-- Durée -->
    <div class="form-group">
        @Html.LabelFor(model => model.Duree, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Duree, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Duree, "", new { @class = "text-danger" })
        </div>
    </div>

    <!-- Date -->
    <div class="form-group">
        @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Ajouter" class="btn btn-success" />
            @Html.ActionLink("Retour à la liste", "Index", null, new { @class = "btn btn-default" })
        </div>
    </div>
</div>
}

Projet_Isi/Projet_Isi/Views/Cours/Index.cshtml
@model System.Data.DataTable
@using System.Data;

@{
    ViewBag.Title = "Liste des Cours";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Model != null)
{
        <div class="container">
            <div class="col-md-8 col-sm-8">
                <div class="blanc">
                    <h1>Liste des Cours</h1>
                </div>

                <table class="table table-bordered table-striped table-responsive">
                    <thead>
                        <tr>
                            <th>ID Cours</th>
                            <th>Nom du Cours</th>
                            <th> Description</th>
                            <th> Nom du Prof</th>
                            <th> Durée</th>
                            <th>Date</th>
                            <th style="width:80px"> Ajouter</th>
                            <th style="width:80px"> Modifier</th>
                            <th style="width:80px"> Supprimer</th>
                        </tr>
                    </thead>
                    @foreach (DataRow dataRow in Model.Rows)
                    {
                        <tr>
                            @foreach (var item in dataRow.ItemArray)
                            {
                                <td>
                                    @item.ToString()
                                </td>

                            }
                            <td style="text-align:center;">
                                <span>
                                    <a href="@Url.Action("Ajouter", "Cours", new { id = dataRow[0] })" class="btn btn-default btn-primary">
                                        <i class="bi bi-pencil-fill"></i>
                                    </a>
                                </span>
                            </td>
                            <td style="text-align:center;">
                                <span>
                                    <a href="@Url.Action("Modifier", "Cours", new { id = dataRow[0] })" class="btn btn-default btn-primary">
                                        <i class="bi bi-pencil-fill"></i>
                                    </a>
                                </span>
                            </td>
                            <td style="text-align:center;">
                                <span>
                                    <a href="@Url.Action("Supprimer", "Cours", new { id = dataRow[0] })" class="btn btn-default btn-primary">
                                        <i class="bi bi-trash3-fill"></i>
                                    </a>
                                </span>
                            </td>

                        </tr>
                     }
                </table>
                <div class="form-group">
                    <div class="col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3">
                         @Html.ActionLink("Retourner à l'accueil", "Index", "Home", null, new { @class = "btn btn-default btn-primary" })
                    </div>
                </div>
            </div>
        </div>
}

Projet_Isi/Projet_Isi/Views/Cours/Modifier.cshtml
@model Projet_Isi.Models.Metier.Cours
@{
    ViewBag.Title = "Modifier un Cours";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Modifier un Cours</h2>

@if (Model != null)
{
    <div class="container">
        <div class="col-md-8 col-sm-8">
            <div class="blanc">
                <h1>Modifier un Cours</h1>
            </div>

            @using (Html.BeginForm("Modifier", "Cours", FormMethod.Post))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <!-- ID Cours -->
                    <div class="form-group">
                        @Html.LabelFor(model => model.Id_cours, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Id_cours, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                            @Html.ValidationMessageFor(model => model.Id_cours, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <!-- Nom du Cours -->
                    <div class="form-group">
                        @Html.LabelFor(model => model.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <!-- Description -->
                    <div class="form-group">
                        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <!-- Nom du Prof -->
                    <div class="form-group">
                        @Html.LabelFor(model => model.Nom_prof, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Nom_prof, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Nom_prof, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <!-- Durée -->
                    <div class="form-group">
                        @Html.LabelFor(model => model.Duree, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Duree, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Duree, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <!-- Date -->
                    <div class="form-group">
                        @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <!-- Ajoutez ici les autres champs du Cours -->

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Enregistrer" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
}

Projet_Isi/Projet_Isi/Views/Cours/Supprimer.cshtml
@model Projet_Isi.Models.Metier.Cours

@{
    ViewData["Title"] = "Supprimer un Cours";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Supprimer un Cours</h2>

<div>
    <h4>Cours</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nom_prof)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nom_prof)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Duree)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Duree)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Supprimer" class="btn btn-danger" /> |
            @Html.ActionLink("Retour à la liste", "Index")
        </div>
    }
</div>